Repository AxonFramework/extension-multitenancy, pull requests merged in 2024-07, with the labels that each got.

#209 Upgrade Axon Framework to 4.10.0
  pom.xml
Labels: Priority 1: Must, Type: Dependency Upgrade

#206 Persistent streams
  multitenancy-spring-boot-3-integrationtests/pom.xml
  multitenancy-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/multitenancy/autoconfig/MultiTenancyAxonServerAutoConfiguration.java
  multitenancy-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/multitenancy/autoconfig/MultiTenantPersistentStreamAutoConfiguration.java
  multitenancy-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/multitenancy/autoconfig/MultiTenantPersistentStreamMessageSource.java
  multitenancy-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/multitenancy/autoconfig/TenantPersistentStreamMessageSourceFactory.java
  multitenancy-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  multitenancy-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/multitenancy/autoconfig/MultiTenancyAutoConfigurationTest.java
  multitenancy-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/multitenancy/autoconfig/MultiTenantPersistentStreamMessageSourceTest.java
  multitenancy/pom.xml
  multitenancy/src/main/java/org/axonframework/extensions/multitenancy/components/MultiTenantAwareComponent.java
  multitenancy/src/main/java/org/axonframework/extensions/multitenancy/components/eventstore/MultiTenantEventStore.java
  multitenancy/src/main/java/org/axonframework/extensions/multitenancy/components/eventstore/MultiTenantSubscribableMessageSource.java
  multitenancy/src/main/java/org/axonframework/extensions/multitenancy/configuration/MultiTenantEventProcessingModule.java
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Feature

#210 Incorrect Spring Boot Auto-configuration ordering
  multitenancy-spring-boot-autoconfigure/src/main/java/org/axonframework/extensions/multitenancy/autoconfig/MultiTenancyAxonServerAutoConfiguration.java
  multitenancy-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/multitenancy/autoconfig/MultiTenancyAutoConfigurationTest.java
Labels: Priority 1: Must, Type: Bug
